// import React from "react";
// import { CheckCircle, XCircle, Clock, MoreHorizontal } from "lucide-react";

// const FundHistory = () => {
//   // Sample data for the table
//   const transactions = [
//     {
//       id: 1,
//       memberId: "PRN676277",
//       pinUnits: 5,
//       package: "Basic Package",
//       amount: 150,
//       date: "2025-06-15T14:30:00",
//       generatedBy: "Admin1",
//       status: "Success",
//     },
//     {
//       id: 2,
//       memberId: "PRN676278",
//       pinUnits: 3,
//       package: "Silver Package",
//       amount: 150,
//       date: "2025-06-16T10:15:00",
//       generatedBy: "Admin2",
//       status: "Success",
//     },
//     {
//       id: 3,
//       memberId: "PRN676279",
//       pinUnits: 2,
//       package: "Gold Package",
//       amount: 200,
//       date: "2025-06-17T16:45:00",
//       generatedBy: "Admin1",
//       status: "Pending",
//     },
//     {
//       id: 4,
//       memberId: "PRN676280",
//       pinUnits: 1,
//       package: "Platinum Package",
//       amount: 200,
//       date: "2025-06-18T09:20:00",
//       generatedBy: "Admin3",
//       status: "Failed",
//     },
//     {
//       id: 5,
//       memberId: "PRN676281",
//       pinUnits: 4,
//       package: "Basic Package",
//       amount: 120,
//       date: "2025-06-19T11:30:00",
//       generatedBy: "Admin2",
//       status: "Success",
//     },
//   ];

//   // Format date
//   const formatDate = (dateString: string) => {
//     const date = new Date(dateString);
//     return date.toLocaleDateString("en-IN", {
//       day: "2-digit",
//       month: "short",
//       year: "numeric",
//       hour: "2-digit",
//       minute: "2-digit",
//     });
//   };

//   // Status component
//   const StatusBadge = ({ status }: { status: string }) => {
//     switch (status.toLowerCase()) {
//       case "success":
//         return (
//           <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
//             <CheckCircle className="mr-1 h-3 w-3" />
//             Success
//           </span>
//         );
//       case "pending":
//         return (
//           <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800">
//             <Clock className="mr-1 h-3 w-3" />
//             Pending
//           </span>
//         );
//       case "failed":
//         return (
//           <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
//             <XCircle className="mr-1 h-3 w-3" />
//             Failed
//           </span>
//         );
//       default:
//         return (
//           <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
//             Unknown
//           </span>
//         );
//     }
//   };

//   return (
//     <div className="min-h-screen bg-gray-50 py-6 px-4">
//       <div className="max-w-7xl mx-auto">
//         {/* Header */}
//         <div className="mb-8">
//           <h1 className="text-2xl font-bold text-gray-900">Fund History</h1>
//           <p className="text-gray-600 mt-1">
//             View all fund transfer transactions
//           </p>
//         </div>

//         {/* Table */}
//         <div className="bg-white shadow-sm rounded-lg overflow-hidden border border-gray-200">
//           <div className="overflow-x-auto">
//             <table className="min-w-full divide-y divide-gray-200">
//               <thead className="bg-gray-800">
//                 <tr>
//                   <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
//                     SL No.
//                   </th>
//                   <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
//                     Member ID
//                   </th>
//                   <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
//                     Pin Units
//                   </th>
//                   <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
//                     Package
//                   </th>
//                   <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
//                     Amount
//                   </th>
//                   <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
//                     Date
//                   </th>
//                   <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
//                     Generated By
//                   </th>
//                   <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
//                     Status
//                   </th>
//                   <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
//                     Action
//                   </th>
//                 </tr>
//               </thead>
//               <tbody className="bg-white divide-y divide-gray-200">
//                 {transactions.map((transaction) => (
//                   <tr key={transaction.id} className="hover:bg-gray-50">
//                     <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
//                       {transaction.id}
//                     </td>
//                     <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600">
//                       {transaction.memberId}
//                     </td>
//                     <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
//                       {transaction.pinUnits}
//                     </td>
//                     <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
//                       {transaction.package}
//                     </td>
//                     <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
//                       ${transaction.amount}
//                     </td>
//                     <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
//                       {formatDate(transaction.date)}
//                     </td>
//                     <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
//                       {transaction.generatedBy}
//                     </td>
//                     <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
//                       <StatusBadge status={transaction.status} />
//                     </td>
//                     <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
//                       <button className="text-gray-400 hover:text-gray-600">
//                         <MoreHorizontal className="h-4 w-4" />
//                       </button>
//                     </td>
//                   </tr>
//                 ))}
//               </tbody>
//             </table>
//           </div>

//           {/* Pagination */}
//           <div className="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
//             <div className="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
//               <div>
//                 <p className="text-sm text-gray-700">
//                   Showing <span className="font-medium">1</span> to{" "}
//                   <span className="font-medium">5</span> of{" "}
//                   <span className="font-medium">5</span> results
//                 </p>
//               </div>
//               <div>
//                 <nav
//                   className="relative z-0 inline-flex rounded-md shadow-sm -space-x-px"
//                   aria-label="Pagination"
//                 >
//                   <a
//                     href="#"
//                     className="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50"
//                   >
//                     <span className="sr-only">Previous</span>
//                     &larr;
//                   </a>
//                   <a
//                     href="#"
//                     aria-current="page"
//                     className="z-10 bg-blue-50 border-blue-500 text-blue-600 relative inline-flex items-center px-4 py-2 border text-sm font-medium"
//                   >
//                     1
//                   </a>
//                   <a
//                     href="#"
//                     className="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"
//                   >
//                     2
//                   </a>
//                   <a
//                     href="#"
//                     className="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50"
//                   >
//                     <span className="sr-only">Next</span>
//                     &rarr;
//                   </a>
//                 </nav>
//               </div>
//             </div>
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default FundHistory;

import React, { useState } from "react";
import {
  CheckCircle,
  XCircle,
  Clock,
  MoreHorizontal,
  Search,
  Edit,
} from "lucide-react";

const FundHistory = () => {
  // Sample data for the table
  const transactions = [
    {
      id: 1,
      memberId: "PRN676277",
      memberName: "John Doe",
      amount: 150,
      date: "2025-06-15T14:30:00",
      transferType: "Main Wallet",
      status: "Success",
    },
    {
      id: 2,
      memberId: "PRN676278",
      memberName: "Jane Smith",
      amount: 200,
      date: "2025-06-16T10:15:00",
      transferType: "Re Top-up Wallet",
      status: "Success",
    },
    {
      id: 3,
      memberId: "PRN676279",
      memberName: "Robert Johnson",
      amount: 300,
      date: "2025-06-17T16:45:00",
      transferType: "Main Wallet",
      status: "Success",
    },
    {
      id: 4,
      memberId: "PRN676280",
      memberName: "Emily Davis",
      amount: 175,
      date: "2025-06-18T09:20:00",
      transferType: "Re Top-up Wallet",
      status: "Success",
    },
    {
      id: 5,
      memberId: "PRN676281",
      memberName: "Michael Wilson",
      amount: 250,
      date: "2025-06-19T11:30:00",
      transferType: "Main Wallet",
      status: "Success",
    },
  ];

  // State for filters
  const [filters, setFilters] = useState({
    memberId: "",
    dateFrom: "",
    dateTo: "",
    transferType: "",
  });

  // State for edit modal
  const [editModal, setEditModal] = useState({
    isOpen: false,
    transaction: null,
    adjustment: "",
    adjustmentType: "add", // 'add' or 'subtract'
  });

  // Handle filter changes
  const handleFilterChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target;
    setFilters({
      ...filters,
      [name]: value,
    });
  };

  // Filter transactions
  const filteredTransactions = transactions.filter((transaction) => {
    return (
      (filters.memberId === "" ||
        transaction.memberId.includes(filters.memberId)) &&
      (filters.dateFrom === "" ||
        new Date(transaction.date) >= new Date(filters.dateFrom)) &&
      (filters.dateTo === "" ||
        new Date(transaction.date) <= new Date(filters.dateTo + "T23:59:59")) &&
      (filters.transferType === "" ||
        transaction.transferType === filters.transferType)
    );
  });

  // Format date
  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  // Open edit modal
  const openEditModal = (transaction: any) => {
    setEditModal({
      isOpen: true,
      transaction,
      adjustment: "",
      adjustmentType: "add",
    });
  };

  // Close edit modal
  const closeEditModal = () => {
    setEditModal({
      isOpen: false,
      transaction: null,
      adjustment: "",
      adjustmentType: "add",
    });
  };

  // Handle adjustment change
  const handleAdjustmentChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target;
    setEditModal({
      ...editModal,
      [name]: value,
    });
  };

  // Submit adjustment
  const submitAdjustment = () => {
    // Here you would typically make an API call to update the transaction
    console.log("Adjustment submitted:", editModal);
    closeEditModal();
  };

  return (
    <div className="min-h-screen bg-gray-50 py-6 px-4">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-gray-900">Fund History</h1>
          <p className="text-gray-600 mt-1">
            View all fund transfer transactions
          </p>
        </div>

        {/* Filters */}
        <div className="bg-white shadow-sm rounded-lg overflow-hidden border border-gray-200 mb-6 p-4">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label
                htmlFor="memberId"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Member ID
              </label>
              <input
                type="text"
                id="memberId"
                name="memberId"
                value={filters.memberId}
                onChange={handleFilterChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                placeholder="Search by ID"
              />
            </div>
            <div>
              <label
                htmlFor="dateFrom"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Date From
              </label>
              <input
                type="date"
                id="dateFrom"
                name="dateFrom"
                value={filters.dateFrom}
                onChange={handleFilterChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
            <div>
              <label
                htmlFor="dateTo"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Date To
              </label>
              <input
                type="date"
                id="dateTo"
                name="dateTo"
                value={filters.dateTo}
                onChange={handleFilterChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
            <div>
              <label
                htmlFor="transferType"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Transfer Type
              </label>
              <select
                id="transferType"
                name="transferType"
                value={filters.transferType}
                onChange={handleFilterChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="">All Types</option>
                <option value="Main Wallet">Main Wallet</option>
                <option value="Re Top-up Wallet">Re Top-up Wallet</option>
              </select>
            </div>
          </div>
          <div className="mt-4 flex justify-end">
            <button
              className="px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              onClick={() =>
                setFilters({
                  memberId: "",
                  dateFrom: "",
                  dateTo: "",
                  transferType: "",
                })
              }
            >
              Reset Filters
            </button>
          </div>
        </div>

        {/* Table */}
        <div className="bg-white shadow-sm rounded-lg overflow-hidden border border-gray-200">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-800">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                    SL No.
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                    Date
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                    Member ID
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                    Member Name
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                    Amount
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                    Transfer Type
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredTransactions.map((transaction) => (
                  <tr key={transaction.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {transaction.id}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {formatDate(transaction.date)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-blue-600">
                      {transaction.memberId}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {transaction.memberName}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      ${transaction.amount}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {transaction.transferType}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                        <CheckCircle className="mr-1 h-3 w-3" />
                        Success
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      <button
                        onClick={() => openEditModal(transaction)}
                        className="text-blue-600 hover:text-blue-900 mr-3"
                      >
                        <Edit className="h-4 w-4" />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div className="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
            <div className="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
              <div>
                <p className="text-sm text-gray-700">
                  Showing <span className="font-medium">1</span> to{" "}
                  <span className="font-medium">
                    {filteredTransactions.length}
                  </span>{" "}
                  of{" "}
                  <span className="font-medium">
                    {filteredTransactions.length}
                  </span>{" "}
                  results
                </p>
              </div>
              <div>
                <nav
                  className="relative z-0 inline-flex rounded-md shadow-sm -space-x-px"
                  aria-label="Pagination"
                >
                  <button className="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                    <span className="sr-only">Previous</span>
                    &larr;
                  </button>
                  <button
                    aria-current="page"
                    className="z-10 bg-blue-50 border-blue-500 text-blue-600 relative inline-flex items-center px-4 py-2 border text-sm font-medium"
                  >
                    1
                  </button>
                  <button className="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium">
                    2
                  </button>
                  <button className="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50">
                    <span className="sr-only">Next</span>
                    &rarr;
                  </button>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Edit Modal */}
      {editModal.isOpen && (
        <div className="fixed z-10 inset-0 overflow-y-auto">
          <div className="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
            <div
              className="fixed inset-0 transition-opacity"
              aria-hidden="true"
            >
              <div className="absolute inset-0 bg-gray-500 opacity-75"></div>
            </div>
            <span
              className="hidden sm:inline-block sm:align-middle sm:h-screen"
              aria-hidden="true"
            >
              &#8203;
            </span>
            <div className="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
              <div className="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                <h3 className="text-lg leading-6 font-medium text-gray-900 mb-4">
                  Adjust Transaction Amount
                </h3>
                <div className="mb-4">
                  <p className="text-sm text-gray-500">
                    Member: {editModal.transaction.memberName} (
                    {editModal.transaction.memberId})
                  </p>
                  <p className="text-sm text-gray-500">
                    Original Amount: ${editModal.transaction.amount}
                  </p>
                  <p className="text-sm text-gray-500">
                    Date: {formatDate(editModal.transaction.date)}
                  </p>
                </div>
                <div className="mb-4">
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Adjustment Type
                  </label>
                  <select
                    name="adjustmentType"
                    value={editModal.adjustmentType}
                    onChange={handleAdjustmentChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                  >
                    <option value="add">Add Amount</option>
                    <option value="subtract">Subtract Amount</option>
                  </select>
                </div>
                <div className="mb-4">
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Adjustment Amount
                  </label>
                  <input
                    type="number"
                    name="adjustment"
                    value={editModal.adjustment}
                    onChange={handleAdjustmentChange}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                    placeholder="Enter amount"
                  />
                </div>
                <div className="mb-4">
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    New Amount
                  </label>
                  <div className="px-3 py-2 bg-gray-100 rounded-md">
                    {editModal.adjustmentType === "add"
                      ? `$${
                          editModal.transaction.amount +
                          (Number(editModal.adjustment) || 0)
                        }`
                      : `$${
                          editModal.transaction.amount -
                          (Number(editModal.adjustment) || 0)
                        }`}
                  </div>
                </div>
              </div>
              <div className="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                <button
                  type="button"
                  onClick={submitAdjustment}
                  className="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-blue-600 text-base font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 sm:ml-3 sm:w-auto sm:text-sm"
                >
                  Confirm Adjustment
                </button>
                <button
                  type="button"
                  onClick={closeEditModal}
                  className="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default FundHistory;
